// Figureout-only content. Do not reuse the finance/health apps' disclosures.
// Owner must approve operator/contact, eligibility, retention and moderation operations before publishing.
export const site = {
  origin: 'https://axpocreation.com',
  app: 'figureout - The game night',
  operator: 'Ashish Debnath / AXPO Creations',
  email: 'aaxpocreation@gmail.com',
  updated: 'September 17, 2026',
};

export const pages = [
  { slug: '', label: 'Figureout', title: 'Draw a little. Guess a lot.',
    intro: 'Figureout is a drawing-and-guessing game for iPhone and iPad. Create a room, share its code, or find a match. Take turns drawing an app-selected prompt while the other players guess.',
    sections: [
      { title: 'Your game night, at a glance', items: ['Three or four participants, timed turns, points and end-of-match results.', 'Easy, Medium, Hard and Level up options, with more than 5,000 one- or two-word prompts.', 'Text guesses, room chat and emoji reactions. No microphone or voice chat.', 'Sign in with Apple or Google. Automated practice players can fill empty seats when enabled; they use timed responses, not drawing recognition.'] },
      { title: 'Help, privacy and fair play', paragraphs: ['The pages below explain how Figureout handles your information, how to delete your account, the rules for playing together, and how to contact us. Figureout is separate from AXPO’s expense and wellness products.'] },
    ] },
  { slug: 'privacy-policy', label: 'Privacy policy', title: 'Figureout Privacy Policy',
    intro: 'This policy applies to the Figureout iPhone and iPad app and its multiplayer service. It describes the information we process, why it is needed, who receives it, and your choices.',
    sections: [
      { title: 'Who is responsible', paragraphs: [`${site.operator} operates Figureout. For privacy questions or requests, contact ${site.email}.`] },
      { title: 'Account and sign-in information', paragraphs: ['We store a Figureout user ID, a display name, your Apple or Google provider-specific account identifier, your chosen difficulty, and account/session timestamps. Apple and Google verify your identity; Figureout does not receive your Apple or Google password.', 'Apple authorization credentials needed to revoke access are encrypted on the server. Figureout sessions are stored securely in the device Keychain; the server stores session-token hashes. Google’s SDK also manages its sign-in credentials on your device.', 'A sign-in provider may include an email address or profile information in its identity response. The current Figureout database does not store a profile email or photo. If you email support, we receive your email address and the information you send. Your display name is visible to other players, so avoid using sensitive personal information.'] },
      { title: 'Gameplay, safety and device information', items: ['Rooms and membership, drawings as stroke coordinates, guesses, chat messages, reactions, turn timing, scores and results are processed on our server to run the match. Other participants can see shared game content, but not your sign-in credentials or private prompt choices.', 'A bounded recent-prompt history is linked to your account to reduce repeated words. Difficulty is stored with your account. Sound preferences are stored locally using UserDefaults.', 'If you report a player, we store the reporter/target account IDs, reason, optional details, relevant recent messages and the reported player’s current drawing when available. Reports are visible to authorized operators, not other players. We store blocks and temporary multiplayer restrictions to enforce safety actions.', 'Google Cloud may process IP addresses, request metadata, timestamps and operational/security logs when serving traffic. The application hashes IP addresses for short-lived abuse rate limits and avoids logging authorization headers, request bodies and drawing/chat content as routine request logs.'] },
      { title: 'Why we use information', paragraphs: ['We use necessary account and gameplay data to authenticate you, connect players, synchronize a match, award points, save preferences and avoid recent prompts. Safety and technical information helps us prevent abuse, investigate reports, support users and keep the service reliable. We do not sell personal information or use gameplay drawings to train AI models.', 'Where a legal basis is required, we rely on providing the service you request, legitimate interests in security and fair play where permitted, and applicable legal duties. Optional support content is provided by you. You can stop playing, sign out or delete your account. We do not seek blanket permission for unrelated uses.'] },
      { title: 'Service providers and sharing', paragraphs: ['Google Cloud hosts the API and PostgreSQL database in the configured Mumbai region (asia-south1). Apple provides Sign in with Apple; Google provides Google Sign-In. Their services, infrastructure and support systems can process information in other countries. Providers have their own privacy terms and we use them to supply the service, not to sell your information.', 'Information may be disclosed when necessary to comply with a valid legal obligation, protect users and rights, or investigate misuse. Authorized support/moderation personnel have access only for those duties. Anyone in a room can copy or screenshot visible content; do not post information you want to keep private.'] },
      { title: 'No ads, tracking or sensitive device permissions', paragraphs: ['This release does not integrate advertising, cross-app tracking, a separate product-analytics service, in-app purchases or subscriptions. Figureout does not request your contacts, precise location, microphone, camera, photo library or health data. Drawing input comes from touch or Apple Pencil, not a camera.', 'The bundled Google Sign-In SDK has its own privacy disclosures covering name, email, phone number, user/device identifiers, approximate location, other data and usage data for functionality and some analytics purposes. Which fields are processed depends on the sign-in flow and provider configuration; Figureout requests no extra Google scopes beyond basic sign-in and does not save phone numbers in its account database. Google states that it may use IP addresses to estimate general location for fraud prevention. SDK processing is distinct from Figureout’s own stored gameplay data.'], links: [{ label: 'Google Sign-In data disclosure', href: 'https://developers.google.com/identity/sign-in/ios/app-privacy' }, { label: 'Google privacy policy', href: 'https://policies.google.com/privacy' }, { label: 'Apple privacy policy', href: 'https://www.apple.com/legal/privacy/' }] },
      { title: 'Retention and deletion', paragraphs: ['Account data and recent-prompt history remain until you delete your account. Sessions expire after 30 days; sign-in challenges expire after five minutes. The service cleans expired records during scheduled in-process cleanup. Inactive room records are eligible for removal after 24 hours without updates; abandoned rooms may be removed sooner. These are cleanup targets, not a guarantee of deletion at an exact second while the service is stopped.', 'Safety reports are eligible for removal after 90 days. Blocks remain until you unblock a player or an involved account is deleted. Account deletion removes profile, sessions, prompt history, blocks and room identity, clears room chat and the account’s current drawing, and erases identifying evidence from reports involving that account. A non-identifying report record may remain until its retention period ends.', 'The current Cloud SQL configuration retains seven automated backups (a count, not a guaranteed seven-day deadline) and seven days of recovery transaction logs. The default operational-log bucket retains logs for 30 days. Google Cloud’s required administrative/audit log bucket has a longer provider-defined retention period; it is not used as game history. These backups and logs are not available as normal game data and can outlive deletion from the active database. Retention may be extended where a specific legal obligation requires it. Contact us for a data request. Uninstalling the app does not remove server data.'] },
      { title: 'Your choices and rights', paragraphs: ['Use the top-right account menu → Delete account from the home lobby for in-app deletion. Sign out only ends that device session. Removing the app or revoking a provider connection alone does not delete Figureout’s account records.', 'Depending on your location, you may have rights to access, correct, delete, restrict or object to certain processing, receive a copy of your data, or complain to a privacy authority. Email us to exercise these rights. We may need proportionate account-ownership verification; never send passwords, sign-in codes, private keys or access tokens.'] },
      { title: 'Age suitability and safety', paragraphs: ['Figureout includes live content created by other players. Follow the age rating shown in your App Store region and any local account-consent requirements. The app is not presented as a Kids Category service. If you believe a child has provided personal information without required permission, contact us so we can investigate and address it.'] },
      { title: 'Security and changes', paragraphs: ['Connections to the production service use encrypted HTTPS/WSS, with authenticated sessions and access controls. No online service can guarantee absolute security. We update this policy when practices change, revise the date above and provide additional notice or consent where required.'] },
    ] },
  { slug: 'terms-of-service', label: 'Terms of use', title: 'Figureout Terms of Use',
    intro: `These terms govern your use of Figureout’s game service, operated by ${site.operator}. By choosing to sign in and use Figureout, you agree to these terms and the Community Guidelines. The Privacy Policy explains data handling. If you do not agree, do not use the service.`,
    sections: [
      { title: 'Eligibility and your account', paragraphs: ['You must satisfy the app’s regional age rating and applicable local requirements to hold an account or provide consent. Obtain parent or guardian permission where required by law. Use your own Apple or Google account, keep access secure, and do not impersonate another person. Different sign-in providers may create separate Figureout accounts.'] },
      { title: 'The game service', paragraphs: ['Figureout’s current game is canvas drawing and guessing. Prompts, timers, scoring and match state are managed by the server. Points have no cash value. Network conditions can affect play. Automated practice participants may fill empty seats when enabled; they use timed guesses and replay drawings. Future games are not included merely because they have been discussed or advertised as future ideas.', 'There are no purchases or subscriptions in this release. If paid features are introduced, their price, terms and required store purchase process will be disclosed before you buy.'] },
      { title: 'App license', paragraphs: ['The iOS app is licensed, not sold, under Apple’s Standard Licensed Application End User License Agreement. These terms govern the Figureout service and do not replace Apple’s standard app license. Follow Apple’s usage rules. You may not unlawfully copy, resell, exploit or interfere with the app, bypass security, cheat, scrape player data or misuse the service.'], links: [{ label: 'Apple’s Standard EULA', href: 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/' }] },
      { title: 'Your drawings and messages', paragraphs: ['You retain rights in content you create. You grant us the limited, non-exclusive permission needed to transmit, display, store and review that content to operate matches, provide support and enforce safety rules. Do not submit content you lack the right to share. This permission is not a sale of your content or a license for unrelated advertising or AI training. Other players may capture what they see.'] },
      { title: 'Community standards and enforcement', paragraphs: ['Do not post sexual content, hate speech, harassment, threats, abusive drawings, personal contact details, scams, unlawful content or material that infringes others’ rights. Do not target children, pressure people to move conversations elsewhere, evade restrictions or make knowingly false reports.', 'We may reject text, remove content, end participation or temporarily restrict multiplayer access for abuse, security or legal reasons. You can report or block players in the app. Blocking leaves the current room and prevents future pairing between the same accounts. Filters do not detect every objectionable drawing or message. Contact support to raise a concern or appeal a restriction. We review reports; this is not an emergency-response service.'] },
      { title: 'Availability, responsibility and consumer rights', paragraphs: ['We aim to provide a reliable game but do not promise uninterrupted availability, error-free scoring or prevention of every harmful act by another user. To the extent permitted by applicable law, the service is provided as available and liability is limited to losses for which we are legally responsible. Nothing here excludes liability or remedies that cannot lawfully be excluded, including mandatory consumer rights.'] },
      { title: 'Leaving, deletion and changes', paragraphs: ['You may stop using the app or delete your account from the account menu. Deletion is permanent and removes the account data described in the Privacy Policy. We may change or discontinue features and will provide notice when legally required. Material updates to these terms will be dated and communicated as required; continued use after they take effect is subject to the updated terms.'] },
      { title: 'Questions, disputes and rights concerns', paragraphs: [`Contact ${site.email} first for support, appeals, privacy or copyright concerns. Include enough information to identify the issue without sending credentials. These terms do not deprive you of the protection of mandatory law or the courts/authorities available to you under that law.`] },
    ] },
  { slug: 'community-guidelines', label: 'Community guidelines', title: 'Keep game night welcoming',
    intro: 'Draw the prompt, guess the word and treat everyone with respect. These rules apply to display names, drawings, messages and reactions in both public and private rooms.',
    sections: [
      { title: 'Not allowed', items: ['Sexual or exploitative content, especially anything involving children.', 'Hate speech, slurs, harassment, bullying, threats or encouragement of self-harm.', 'Names, phone numbers, email addresses or other private information shared without permission; invitations to move to external chat.', 'Spam, scams, cheating, impersonation, unlawful material and copyright infringement.', 'Knowingly false reports or attempts to evade moderation.'] },
      { title: 'Report and block', paragraphs: ['In a room, open the account menu → Player safety. During a turn, use Match options → Player safety. Select a player and a reason, then send the report. The server saves relevant game evidence and returns a report reference. Use Report & block to report and immediately leave the room, or Block & leave without submitting a report.', 'Blocking prevents future matching or room joining between those accounts, in either direction. It does not control accounts outside Figureout or guarantee detection of someone creating a new account. Manage your own blocks under Your account → Blocked players.', 'You can hide the current drawing on your device immediately from Match options while deciding whether to report or leave. Hidden drawings are not automatically reported.'] },
      { title: 'How safety works', paragraphs: ['Server-side checks reject some offensive text, obvious contact details and links before sharing. Filters are limited and do not understand every language or drawing. Reports need human review. Depending on the evidence, we may remove content or temporarily suspend multiplayer access. Account deletion remains available during a multiplayer restriction.', `For concerns, an appeal or a problem using the report controls, email ${site.email} with your report reference and approximate date. Do not resend harmful media unless support specifically requests it. For imminent danger, contact the appropriate local emergency service.`] },
    ] },
  { slug: 'account-deletion', label: 'Delete account', title: 'Delete your Figureout account',
    intro: 'You can permanently delete your account directly inside Figureout. You do not need to email us for ordinary account deletion.',
    sections: [
      { title: 'In the app', steps: ['Leave any current match to return to the home lobby.', 'Tap the account icon at the top right.', 'Choose Delete account, read the confirmation and select Delete account permanently.', 'Wait for the server response. A successful deletion signs you out. If an error appears, deletion was not confirmed; retry or contact support.'] },
      { title: 'What is removed', paragraphs: ['Your Figureout profile, sessions, difficulty preference, recent-prompt history and blocks are deleted. Room identity is anonymized or removed, room chat is cleared and any current drawing associated with your account is cleared. Identifying safety-report evidence involving your account is erased; non-identifying case records can remain up to the report-retention period.', 'Apple authorization is revoked as part of successful deletion. The app also attempts to disconnect Google Sign-In when relevant. If Google cannot be disconnected, your Figureout account can still be deleted and the app explains how to remove Figureout from Google Account connections.', 'Temporary cloud backups and security/operational logs expire under their retention settings, rather than disappearing instantly. Deletion cannot remove screenshots or copies already made independently by other players.'] },
      { title: 'Sign out is different', paragraphs: ['Signing out ends the current Figureout session but preserves your account. Uninstalling the app, removing access in Apple/Google settings or changing devices does not by itself request Figureout account deletion. Signing in again after deletion creates a new account, not a recovery of the old one. If you created separate profiles with Apple and Google, delete each profile separately while signed in with that provider.'] },
      { title: 'Cannot access the app?', paragraphs: [`Email ${site.email} with the subject “Figureout account deletion” and describe the sign-in method and issue. We will explain proportionate ownership verification before acting. Do not send a password, OTP, identity token or private key. A support email is an alternative for access problems, not a required extra step for in-app deletion.`] },
    ] },
  { slug: 'support', label: 'Help & support', title: 'Figureout Help & Support',
    intro: 'Need help with a match, your account or player safety? Contact us directly. This page does not ask you to sign in.',
    sections: [
      { title: 'Contact Figureout', paragraphs: [`Email ${site.email}. Include the app version, iPhone/iPad model, approximate time of the problem and a short description. Include a report reference for safety issues. Never send account passwords, sign-in codes, session tokens or private keys. Opening the email link creates a draft in your email app; you still need to send it. This page does not submit a support form.`] },
      { title: 'How to play', paragraphs: ['Sign in, find a match or create a room, then share the six-character room code with friends. Participants take turns choosing from server-provided prompts and drawing while others guess. Accurate guesses earn more points; close answers can earn partial credit. The artist also earns points when others solve the drawing. Select difficulty before a match.', 'A match can start with three participants. When practice-player fallback is enabled, automated participants can fill empty seats. They use timed responses and pre-recorded drawing paths; they do not recognize what you draw.'] },
      { title: 'Troubleshooting', items: ['Players missing? Each human needs a separate signed-in Figureout account. Two devices using the same sign-in account share one player identity.', 'Cannot reconnect? Check internet access, reopen the app and use the same account. An expired room cannot be restored; create a new one.', 'Sound quiet? Check silent mode and the in-app sound controls. Background music is softer during gameplay.', 'Apple and Google sign-ins are separate identities; use the same provider to return to the same account.'] },
      { title: 'Safety, privacy and deletion', paragraphs: ['Use Player safety inside a room to report or block another player. Use the top-right account menu on the home lobby for permanent account deletion. The linked Privacy Policy and Community Guidelines explain the information processed and your options. Contact support if those controls fail.'] },
    ] },
];
